services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-customer
    restart: always
    volumes:
      - mysql_data_customer:/var/lib/mysql
    environment:
      MYSQL_DATABASE: customer-db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    expose:
      - 9999
    environment:
      PMA_HOST: mysql-db-customer
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  inventory-management-config-service:
    build: ./config-service
    container_name: inventory-management-config-service
    ports:
      - '7777:7777'
    expose:
      - '7777'
    environment:
      - DISCOVERY_SERVICE_URL=http://inventory-management-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7777/actuator/health" ]
      interval: 10s
      retries: 4
  inventory-management-discovery-service:
    build: ./discovery-service
    container_name: inventory-management-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      inventory-management-config-service:
        condition: service_healthy
  inventory-management-customer-service:
    build: ./customer-service
    container_name: inventory-management-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
      - DISCOVERY_SERVICE_URL=http://inventory-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://inventory-management-config-service:7777
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      inventory-management-discovery-service:
        condition: service_healthy
  inventory-management-inventory-service:
    build: ./inventory-service
    container_name: inventory-management-inventory-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
      - DISCOVERY_SERVICE_URL=http://inventory-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://inventory-management-config-service:7777
    depends_on:
      inventory-management-customer-service:
        condition: service_healthy
  inventory-management-gateway-service:
    build: ./gateway
    container_name: inventory-management-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://inventory-management-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://inventory-management-config-service:7777
    depends_on:
      inventory-management-discovery-service:
        condition: service_healthy
volumes:
  mysql_data_customer: